### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by pixelguy95** [Johnstedt/Tremory_Lib#1]
In **PointFetch.js** in **getPointsFromCurrentUser()** there is an attempt to fetch the user id of the currently logged in user. The function doesn't exist however, and I am not sure that it should. Doesn't setting id to 0 have the same effect?

I don't think the library should refer to locally stored varialbes at all if possible

**Comment by Johnstedt** [comment]
Yes, thought I removed all of them. I guess not.

fix:
https://github.com/Johnstedt/Tremory_Lib/commit/41d40bc120e35a6e08dbb9901add74d86fff7677
